spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled:true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    listener:
      type: batch       # 단일 레코드가 아닌 배치 단위로 리스너에 전달
      ack-mode: MANUAL  # 정상 처리 시 명시적 ack.acknowledge() 호출 필요

    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      max-poll-records: 50   # 한 번에 가져올 최대 레코드 수
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081



